services:
  server:
    image: gianluisdiana/metaspesa_server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 5000:8080
    environment:
      ASPNETCORE_URLS: http://+:8080

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: gianluisdiana/metaspesa_client:latest
    ports:
      - 3000:8080
    depends_on:
      - server
    environment:
      GRPC_SERVER_URL: server:8080
      PORT: 8080